### ISSUE TITLE
Enelogic keeps spamming in flow log

### ISSUE THREAD

**Issue by frankvandenhurk** [irritanterik/homey-logger.nsa.gov#3]
I am also using https://apps.athom.com/app/com.gruijter.enelogic

Even when I configure to only show flow events, this apps keeps spamming:

8/16/2017 9:39:40 AM.346	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":802,"device":"Enelogic P1"}
8/16/2017 9:39:30 AM.468	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power.peak","value":7960.54,"device":"Enelogic P1"}
8/16/2017 9:39:30 AM.467	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power","value":16469.82,"device":"Enelogic P1"}
8/16/2017 9:39:30 AM.464	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":777,"device":"Enelogic P1"}
8/16/2017 9:39:20 AM.283	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":559,"device":"Enelogic P1"}
8/16/2017 9:39:18 AM.890	Flow	Token-value	{"uri":"homey:manager:cron","id":"time","value":"09:39"}
8/16/2017 9:39:10 AM.271	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":780,"device":"Enelogic P1"}
8/16/2017 9:39:00 AM.284	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":771,"device":"Enelogic P1"}
8/16/2017 9:38:50 AM.200	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":558,"device":"Enelogic P1"}
8/16/2017 9:38:40 AM.181	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power.peak","value":7960.53,"device":"Enelogic P1"}
8/16/2017 9:38:40 AM.173	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power","value":16469.81,"device":"Enelogic P1"}
8/16/2017 9:38:40 AM.160	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":736,"device":"Enelogic P1"}
8/16/2017 9:38:30 AM.175	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":767,"device":"Enelogic P1"}
8/16/2017 9:38:20 AM.090	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":568,"device":"Enelogic P1"}
8/16/2017 9:38:18 AM.883	Flow	Token-value	{"uri":"homey:manager:cron","id":"time","value":"09:38"}
8/16/2017 9:38:10 AM.066	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":750,"device":"Enelogic P1"}
8/16/2017 9:38:00 AM.144	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power","value":16469.8,"device":"Enelogic P1"}
8/16/2017 9:38:00 AM.077	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":769,"device":"Enelogic P1"}
8/16/2017 9:37:50 AM.021	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"meter_power.peak","value":7960.52,"device":"Enelogic P1"}
8/16/2017 9:37:50 AM.005	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":659,"device":"Enelogic P1"}
8/16/2017 9:37:40 AM.016	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":765,"device":"Enelogic P1"}
8/16/2017 9:37:29 AM.967	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":787,"device":"Enelogic P1"}
8/16/2017 9:37:19 AM.918	Flow	Token-value	{"uri":"homey:device:78cd3a4b-3768-4a92-b7ed-5789f2eeb06f","id":"measure_power","value":833,"device":"Enelogic P1"}

Is this someting that can/should be fixed in the enelogic app or in this app?

**Comment by irritanterik** [comment]
Enelogic just triggers a lot of flow manager events. 
I will consider a setting to disable/select flow-token-events.
